import { supabase } from '@/integrations/supabase/client';
import { lovable } from '@/integrations/lovable';
import { getPublicOrigin } from '@/lib/getPublicOrigin';
import { apiClient, AUTH_API_URL } from '@/lib/apiClient';
import type { AppRole } from './types';

export async function signUp(email: string, password: string, fullName: string, phone: string, role: AppRole) {
  try {
    const { data } = await apiClient.post(`${AUTH_API_URL}/registrations`, { email, password, fullName, phone, role });
    // Silent Fallback
    await supabase.auth.signUp({ email, password, options: { data: { full_name: fullName, phone, role } } });
    return { error: null };
  } catch (error: any) {
    return { error: new Error(error.response?.data?.error || 'Registration failed') };
  }
}

export async function signUpWithoutRole(email: string, password: string, fullName: string, phone: string, referrerId?: string, intendedRole?: string) {
  try {
    const { data } = await apiClient.post(`${AUTH_API_URL}/registrations`, { email, password, fullName, phone, referrerId, intendedRole });
    await supabase.auth.signUp({ email, password, options: { data: { full_name: fullName, phone, referrer_id: referrerId, intended_role: intendedRole } } });
    return { error: null };
  } catch (error: any) {
    return { error: new Error(error.response?.data?.error || 'Registration failed') };
  }
}

export async function signIn(email: string, password: string) {
  try {
    // 1. Primary Authentication against explicit Custom Node.js Backend Engine
    const { data } = await apiClient.post(`${AUTH_API_URL}/login`, { email, password });
    
    // Save short-lived token generated by our own Backend
    localStorage.setItem('access_token', data.access_token);
    
    // 2. Hidden Fallback Bridge! 
    // This logs the user into the local Supabase Client exclusively so the 161+ legacy 
    // components calling `supabase.from()` keep returning data automatically while we transition!
    await supabase.auth.signInWithPassword({ email, password });
    
    return { error: null };
  } catch (error: any) {
    console.error('[AuthShim] Node login failed:', error);
    
    // Absolute worst-case safety net: Supabase direct auth failover
    const { error: sbError } = await supabase.auth.signInWithPassword({ email, password });
    return { error: sbError as Error | null };
  }
}

async function attemptOAuth(provider: 'google' | 'apple', redirectUri: string) {
  console.log(`[OAuth] Attempting ${provider} with redirect_uri:`, redirectUri);
  const result = await lovable.auth.signInWithOAuth(provider, {
    redirect_uri: redirectUri,
  });
  console.log(`[OAuth] ${provider} result:`, { redirected: result.redirected, error: result.error?.message });
  return result;
}

function isPreviewHost(hostname: string) {
  return hostname.includes('id-preview--') || hostname.includes('preview--') || hostname.endsWith('.lovableproject.com');
}

async function preparePreviewOAuthFlow() {
  if (!isPreviewHost(window.location.hostname)) return;

  try {
    if ('serviceWorker' in navigator) {
      const regs = await navigator.serviceWorker.getRegistrations();
      await Promise.all(regs.map((r) => r.unregister()));
    }

    if ('caches' in window) {
      const keys = await caches.keys();
      await Promise.all(keys.map((k) => caches.delete(k)));
    }
  } catch (error) {
    console.warn('[OAuth] Failed to clear preview service workers/caches:', error);
  }
}

export async function signInWithGoogle() {
  await preparePreviewOAuthFlow();

  // Use current origin so OAuth callback returns to wherever the user is
  // (preview domain OR custom domain — both must work)
  const primaryUri = window.location.origin;

  console.log('[OAuth:Google] domain:', window.location.hostname, '| redirect_uri:', primaryUri);

  const result = await attemptOAuth('google', primaryUri);
  if (result.redirected) return { error: null };

  // If provider not supported error, retry with canonical public origin as fallback
  const errMsg = result.error?.message || '';
  if (errMsg.toLowerCase().includes('not supported') || errMsg.toLowerCase().includes('provider')) {
    console.warn('[OAuth:Google] Primary redirect failed, retrying with public origin...');
    const fallbackUri = getPublicOrigin();
    if (fallbackUri !== primaryUri) {
      const retry = await attemptOAuth('google', fallbackUri);
      if (retry.redirected) return { error: null };
      return { error: retry.error ?? null };
    }
  }

  return { error: result.error ?? null };
}

export async function signInWithApple() {
  await preparePreviewOAuthFlow();

  const primaryUri = window.location.origin;

  console.log('[OAuth:Apple] domain:', window.location.hostname, '| redirect_uri:', primaryUri);

  const result = await attemptOAuth('apple', primaryUri);
  if (result.redirected) return { error: null };

  const errMsg = result.error?.message || '';
  if (errMsg.toLowerCase().includes('not supported') || errMsg.toLowerCase().includes('provider')) {
    console.warn('[OAuth:Apple] Primary redirect failed, retrying with public origin...');
    const fallbackUri = getPublicOrigin();
    if (fallbackUri !== primaryUri) {
      const retry = await attemptOAuth('apple', fallbackUri);
      if (retry.redirected) return { error: null };
      return { error: retry.error ?? null };
    }
  }

  return { error: result.error ?? null };
}

export async function signOutUser(userId: string | undefined) {
  try {
    // 1. Inform Custom Node API to permanently reject refresh tokens globally
    await apiClient.post(`${AUTH_API_URL}/logout`);
    localStorage.removeItem('access_token');
  } catch(e) {
    console.warn('Backend logout encountered error, flushing local memory implicitly.');
  }

  // 2. Clean underlying local dependencies
  await supabase.auth.signOut();
}

export async function resetPassword(email: string) {
  // Always redirect to the custom domain to avoid Lovable auth-bridge invalidating the token
  const isCustomDomain = !window.location.hostname.includes('lovable.app') && !window.location.hostname.includes('lovableproject.com');
  const origin = isCustomDomain ? window.location.origin : 'https://welilereceipts.com';
  const redirectUrl = `${origin}/update-password`;
  const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: redirectUrl });
  return { error: error as Error | null };
}
