import { PERMISSIONS, type Permission } from './permissions';
import type { Role } from '../contexts/AuthContext';

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: ['*'],
  CFO: [
    PERMISSIONS.VIEW_LEDGER, 
    PERMISSIONS.VIEW_TRANSACTIONS, 
    PERMISSIONS.APPROVE_WITHDRAWALS
  ],
  COO: [
    PERMISSIONS.VIEW_TRANSACTIONS, 
    PERMISSIONS.VIEW_AGENT_COLLECTIONS, 
    PERMISSIONS.APPROVE_WITHDRAWALS
  ],
  CEO: [
    PERMISSIONS.VIEW_AUDIT, 
    PERMISSIONS.VIEW_TRANSACTIONS, 
    PERMISSIONS.VIEW_LEDGER
  ],
  ADMIN: [
    PERMISSIONS.MANAGE_USERS, 
    PERMISSIONS.APPROVE_DEPOSITS, 
    PERMISSIONS.APPROVE_RENT_REQUESTS
  ],
  CTO: [
    PERMISSIONS.CONFIG_SYSTEM, 
    PERMISSIONS.VIEW_AUDIT
  ],
  CMO: [],
  CRM: [],
  // Consumer roles - tightly isolated permission sets for the Adaptive Portal
  TENANT: [PERMISSIONS.VIEW_OWN_WALLET, PERMISSIONS.VIEW_OWN_RENT_STATUS],
  FUNDER: [PERMISSIONS.VIEW_OWN_WALLET, PERMISSIONS.VIEW_OWN_PORTFOLIO],
  AGENT: [PERMISSIONS.VIEW_OWN_WALLET, PERMISSIONS.MANAGE_OWN_COLLECTIONS],
  LANDLORD: [PERMISSIONS.VIEW_OWN_WALLET, PERMISSIONS.VIEW_OWN_RENT_STATUS]
};
