import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { History, Download, Loader2, Clock, Trash2 } from 'lucide-react';
import { format, formatDistanceToNow } from 'date-fns';
import { formatUGX } from '@/lib/rentCalculations';
import jsPDF from 'jspdf';
import { toast } from 'sonner';

export function DeleteHistoryViewer() {
  const [expanded, setExpanded] = useState(false);

  const { data: deletions, isLoading } = useQuery({
    queryKey: ['rent-request-deletions'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('rent_request_deletions')
        .select('*')
        .gte('expires_at', new Date().toISOString())
        .order('created_at', { ascending: false })
        .limit(50);
      if (error) throw error;
      return data || [];
    },
    staleTime: 60000,
  });

  const downloadSnapshot = (d: any) => {
    try {
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      let y = 20;

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('WELILE — Deleted Rent Request Snapshot', 14, y);
      y += 10;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const lines = [
        `Deleted At: ${format(new Date(d.created_at), 'PPpp')}`,
        `Deleted By: ${d.deleted_by_name}`,
        `Reason: ${d.deletion_reason}`,
        `Expires: ${format(new Date(d.expires_at), 'PPpp')}`,
        '',
        `Tenant: ${d.tenant_name}`,
        `Phone: ${d.tenant_phone || '—'}`,
        `Agent: ${d.agent_name || '—'}`,
        `Agent Phone: ${d.agent_phone || '—'}`,
        '',
        `Rent Amount: UGX ${Number(d.rent_amount).toLocaleString()}`,
        `Total Repayment: UGX ${Number(d.total_repayment).toLocaleString()}`,
        `Amount Repaid: UGX ${Number(d.amount_repaid).toLocaleString()}`,
        `Outstanding: UGX ${Number(d.outstanding).toLocaleString()}`,
        `Daily Repayment: UGX ${Number(d.daily_repayment).toLocaleString()}`,
        `Tenant Wallet: UGX ${Number(d.tenant_wallet).toLocaleString()}`,
        `Disbursed At: ${d.disbursed_at ? format(new Date(d.disbursed_at), 'PPpp') : '—'}`,
        `Previous Status: ${d.request_status}`,
      ];

      lines.forEach(line => {
        doc.text(line, 14, y);
        y += 5;
      });

      y += 5;
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(120, 120, 120);
      doc.text('Generated by Welile Technologies Ltd. This record expires 7 days after deletion.', 14, y);

      doc.save(`deletion-snapshot-${d.tenant_name.replace(/\s+/g, '-')}-${format(new Date(d.created_at), 'yyyyMMdd')}.pdf`);
      toast.success('Snapshot downloaded');
    } catch {
      toast.error('Failed to generate PDF');
    }
  };

  if (!expanded) {
    return (
      <Button
        variant="outline"
        size="sm"
        onClick={() => setExpanded(true)}
        className="w-full h-10 gap-2 text-xs font-semibold text-muted-foreground border-dashed"
      >
        <History className="h-4 w-4" />
        Delete History
        {deletions && deletions.length > 0 && (
          <Badge variant="secondary" className="text-[10px] px-1.5 ml-1">
            {deletions.length}
          </Badge>
        )}
      </Button>
    );
  }

  return (
    <Card className="border shadow-sm border-destructive/20">
      <CardHeader className="pb-2 px-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-sm font-semibold flex items-center gap-2 text-destructive">
            <Trash2 className="h-4 w-4" />
            Delete History (7-day window)
          </CardTitle>
          <Button variant="ghost" size="sm" onClick={() => setExpanded(false)} className="text-xs h-7">
            Hide
          </Button>
        </div>
      </CardHeader>
      <CardContent className="px-3 pb-3">
        {isLoading ? (
          <div className="flex items-center justify-center py-6">
            <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          </div>
        ) : !deletions?.length ? (
          <p className="text-xs text-muted-foreground text-center py-4">No deletions in the last 7 days</p>
        ) : (
          <div className="space-y-2 max-h-[300px] overflow-y-auto">
            {deletions.map(d => (
              <div key={d.id} className="rounded-lg border border-border/50 p-3 space-y-2 bg-muted/30">
                <div className="flex items-center justify-between gap-2">
                  <div className="min-w-0">
                    <p className="text-sm font-medium truncate">{d.tenant_name}</p>
                    <p className="text-[10px] text-muted-foreground">{d.tenant_phone}</p>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => downloadSnapshot(d)}
                    className="h-8 gap-1.5 text-xs shrink-0"
                  >
                    <Download className="h-3.5 w-3.5" />
                    PDF
                  </Button>
                </div>
                <div className="grid grid-cols-2 gap-1 text-[10px]">
                  <span className="text-muted-foreground">Outstanding: <strong className="text-destructive">{formatUGX(d.outstanding)}</strong></span>
                  <span className="text-muted-foreground">Repaid: <strong className="text-emerald-600">{formatUGX(d.amount_repaid)}</strong></span>
                </div>
                <div className="flex items-center gap-2 text-[10px] text-muted-foreground">
                  <Clock className="h-3 w-3" />
                  <span>Deleted {formatDistanceToNow(new Date(d.created_at), { addSuffix: true })} by {d.deleted_by_name}</span>
                </div>
                <p className="text-[10px] text-muted-foreground italic">"{d.deletion_reason}"</p>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
