import jsPDF from 'jspdf';
import { format } from 'date-fns';

interface TenantRentRow {
  tenant_name: string;
  tenant_phone: string;
  start_date: string;
  rent_given: number;
  amount_paid: number;
  outstanding: number;
  agent_name: string;
  duration_days: number;
  payments_made: number;
}

export function generateTenantOpsReportPdf(tenants: TenantRentRow[]): Blob {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 10;
  const contentWidth = pageWidth - margin * 2;
  let y = 14;

  const ugx = (n: number) => `UGX ${n.toLocaleString()}`;
  const fmtDate = (d: string) => {
    try { return format(new Date(d), 'dd MMM yyyy'); } catch { return '—'; }
  };

  // Header
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('WELILE', margin, y);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(format(new Date(), 'dd MMM yyyy, hh:mm a'), pageWidth - margin, y, { align: 'right' });
  y += 7;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Tenant Rent Report', margin, y);
  y += 6;

  // Summary
  const totalGiven = tenants.reduce((s, t) => s + t.rent_given, 0);
  const totalPaid = tenants.reduce((s, t) => s + t.amount_paid, 0);
  const totalOutstanding = tenants.reduce((s, t) => s + t.outstanding, 0);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Tenants: ${tenants.length}`, margin, y);
  doc.text(`Rent Given: ${ugx(totalGiven)}`, margin + 55, y);
  doc.text(`Total Repaid: ${ugx(totalPaid)}`, margin + 120, y);
  doc.text(`Outstanding: ${ugx(totalOutstanding)}`, margin + 185, y);
  y += 7;

  // Table columns
  const cols = [
    { label: '#', x: margin, w: 7 },
    { label: 'Tenant Name', x: margin + 7, w: 36 },
    { label: 'Start Date', x: margin + 43, w: 24 },
    { label: 'Phone', x: margin + 67, w: 26 },
    { label: 'Rent Given', x: margin + 93, w: 26 },
    { label: 'Amount Paid', x: margin + 119, w: 26 },
    { label: 'Outstanding', x: margin + 145, w: 26 },
    { label: 'Agent', x: margin + 171, w: 36 },
    { label: 'Days', x: margin + 207, w: 14 },
    { label: 'Payments', x: margin + 221, w: 18 },
  ];

  const drawHeader = () => {
    doc.setFillColor(30, 30, 60);
    doc.rect(margin, y - 4, contentWidth, 6, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    cols.forEach(c => doc.text(c.label, c.x + 1, y));
    doc.setTextColor(0, 0, 0);
    y += 5;
  };

  drawHeader();

  tenants.forEach((t, i) => {
    if (y > 190) {
      doc.addPage();
      y = 14;
      drawHeader();
    }

    if (i % 2 === 0) {
      doc.setFillColor(245, 245, 250);
      doc.rect(margin, y - 3.5, contentWidth, 5, 'F');
    }

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    doc.text(`${i + 1}`, cols[0].x + 1, y);
    doc.text(t.tenant_name.slice(0, 22), cols[1].x + 1, y);
    doc.text(fmtDate(t.start_date), cols[2].x + 1, y);
    doc.text(t.tenant_phone || '—', cols[3].x + 1, y);
    doc.text(ugx(t.rent_given), cols[4].x + 1, y);

    doc.setTextColor(0, 130, 50);
    doc.text(ugx(t.amount_paid), cols[5].x + 1, y);

    if (t.outstanding > 0) {
      doc.setTextColor(200, 30, 30);
    } else {
      doc.setTextColor(0, 130, 50);
    }
    doc.setFont('helvetica', 'bold');
    doc.text(ugx(t.outstanding), cols[6].x + 1, y);

    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.text(t.agent_name.slice(0, 22), cols[7].x + 1, y);
    doc.text(`${t.duration_days}`, cols[8].x + 1, y);
    doc.text(`${t.payments_made}`, cols[9].x + 1, y);

    y += 5;
  });

  // Totals row
  y += 3;
  if (y > 190) { doc.addPage(); y = 14; }
  doc.setFillColor(30, 30, 60);
  doc.rect(margin, y - 4, contentWidth, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTALS', cols[1].x + 1, y);
  doc.text(ugx(totalGiven), cols[4].x + 1, y);
  doc.text(ugx(totalPaid), cols[5].x + 1, y);
  doc.text(ugx(totalOutstanding), cols[6].x + 1, y);
  doc.setTextColor(0, 0, 0);

  // Footer
  y += 12;
  if (y > 195) { doc.addPage(); y = 14; }
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by Welile Technologies Ltd. This is an automated report.', margin, y);
  doc.text(`Report date: ${format(new Date(), 'PPpp')}`, margin, y + 4);

  return doc.output('blob');
}
