import React from 'react';
import { useAuth } from '../../contexts/AuthContext';

const ceoColors = `
  .bg-surface { background-color: #f7f9fb; }
  .text-on-surface { color: #191c1e; }
  .bg-surface-container-lowest { background-color: #ffffff; }
  .bg-surface-container-low { background-color: #f2f4f6; }
  .bg-surface-container { background-color: #eceef0; }
  .bg-surface-container-high { background-color: #e6e8ea; }
  .bg-surface-container-highest { background-color: #e0e3e5; }
  
  .text-on-surface-variant { color: #45464d; }
  .text-on-surface { color: #191c1e; }
  
  .bg-primary { background-color: #000000; }
  .text-on-primary { color: #ffffff; }
  .bg-primary-fixed { background-color: #dae2fd; }
  .bg-primary-fixed-dim { background-color: #bec6e0; }
  .text-on-primary-fixed { color: #131b2e; }
  .text-on-primary-container { color: #7c839b; }
  .bg-on-primary-container { background-color: #7c839b; }
  
  .bg-secondary-fixed { background-color: #d5e3fc; }
  .bg-secondary-fixed-dim { background-color: #b9c7df; }
  .text-on-secondary-fixed { color: #0d1c2e; }
  .text-on-secondary-container { color: #57657a; }
  
  .bg-tertiary-fixed { background-color: #6ffbbe; }
  .bg-tertiary-fixed-dim { background-color: #4edea3; }
  .text-on-tertiary-fixed { color: #002113; }
  .text-on-tertiary-container { color: #009668; }
  
  .bg-error-container { background-color: #ffdad6; }
  .text-on-error-container { color: #93000a; }
  .text-error { color: #ba1a1a; }
  
  .border-outline-variant { border-color: #c6c6cd; }
  
  /* Additional Tailwind Utilities typically generated by Config */
  .divide-outline-variant\\/10 > :not([hidden]) ~ :not([hidden]) {
    border-color: rgba(198, 198, 205, 0.1);
  }
  .bg-tertiary-fixed-dim\\/30 { background-color: rgba(78, 222, 163, 0.3); }
  .bg-secondary-fixed\\/50 { background-color: rgba(213, 227, 252, 0.5); }
  .bg-on-primary-container\\/20 { background-color: rgba(124, 131, 155, 0.2); }
  .bg-error-container\\/40 { background-color: rgba(255, 218, 214, 0.4); }
  .bg-surface-container-low\\/30 { background-color: rgba(242, 244, 246, 0.3); }
  .hover\\:bg-surface-container-low\\/20:hover { background-color: rgba(242, 244, 246, 0.2); }
  .border-outline-variant\\/15 { border-color: rgba(198, 198, 205, 0.15); }
`;

export default function CeoDashboard() {
  const { profile } = useAuth();

  return (
    <div className="bg-surface text-on-surface min-h-screen font-body relative">
      <style>{ceoColors}</style>
      
      {/* SideNavBar */}
      <aside className="h-screen w-64 fixed left-0 top-0 overflow-y-auto bg-slate-100 dark:bg-slate-900 flex flex-col py-8 px-6 z-50">
        <div className="mb-10">
          <h1 className="text-xl font-bold tracking-tight text-slate-900 dark:text-slate-50 font-headline">Sovereign</h1>
          <p className="text-[0.6875rem] font-medium uppercase tracking-widest text-on-surface-variant mt-1">CEO Terminal</p>
        </div>
        
        <nav className="flex-1 space-y-2">
          <a className="flex items-center gap-3 py-2.5 px-3 rounded text-slate-950 dark:text-white font-semibold border-r-2 border-slate-950 dark:border-slate-50 transition-all duration-300" href="#">
            <span className="material-symbols-outlined" data-icon="dashboard">dashboard</span>
            <span className="text-sm">Overview</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 text-slate-500 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800/50 transition-colors duration-200" href="#">
            <span className="material-symbols-outlined" data-icon="payments">payments</span>
            <span className="text-sm">Revenue</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 text-slate-500 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800/50 transition-colors duration-200" href="#">
            <span className="material-symbols-outlined" data-icon="group">group</span>
            <span className="text-sm">Users</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 text-slate-500 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800/50 transition-colors duration-200" href="#">
            <span className="material-symbols-outlined" data-icon="account_balance">account_balance</span>
            <span className="text-sm">Financials</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 text-slate-500 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800/50 transition-colors duration-200" href="#">
            <span className="material-symbols-outlined" data-icon="monitoring">monitoring</span>
            <span className="text-sm">Performance</span>
          </a>
        </nav>
        
        <div className="mt-auto pt-8 border-t border-slate-200 dark:border-slate-800 space-y-2">
          <button className="w-full bg-primary text-on-primary py-2.5 mb-6 text-sm font-semibold rounded active:opacity-80 transition-all">Quick Action</button>
          <a className="flex items-center gap-3 py-2 px-3 text-slate-500 dark:text-slate-400 hover:bg-slate-200/50 transition-colors" href="#">
            <span className="material-symbols-outlined" data-icon="settings">settings</span>
            <span className="text-sm">Settings</span>
          </a>
          <a className="flex items-center gap-3 py-2 px-3 text-slate-500 dark:text-slate-400 hover:bg-slate-200/50 transition-colors" href="#">
            <span className="material-symbols-outlined" data-icon="help_outline">help_outline</span>
            <span className="text-sm">Support</span>
          </a>
        </div>
      </aside>

      {/* TopNavBar */}
      <header className="fixed top-0 right-0 w-[calc(100%-16rem)] h-16 bg-white/80 dark:bg-slate-950/80 backdrop-blur-xl flex justify-between items-center px-10 z-40 border-b border-slate-200/15">
        <div className="flex items-center gap-8">
          <span className="text-lg font-black tracking-tighter text-slate-950 font-headline">Sovereign Intelligence</span>
          <div className="relative">
            <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-sm" data-icon="search">search</span>
            <input className="bg-surface-container-highest border-none rounded-full pl-10 pr-4 py-1.5 text-xs w-64 focus:ring-1 focus:ring-primary focus:bg-surface-container-lowest transition-all" placeholder="Intelligence search..." type="text" />
          </div>
        </div>
        <div className="flex items-center gap-6">
          <button className="text-slate-500 hover:text-slate-950 relative transition-opacity">
            <span className="material-symbols-outlined" data-icon="notifications">notifications</span>
            <span className="absolute top-0 right-0 w-2 h-2 bg-error rounded-full border-2 border-white"></span>
          </button>
          <button className="text-slate-500 hover:text-slate-950 transition-opacity">
            <span className="material-symbols-outlined" data-icon="settings">settings</span>
          </button>
          <div className="flex items-center gap-3 ml-2 cursor-pointer group">
            <div className="text-right">
              <p className="text-xs font-bold uppercase tracking-tight text-slate-950">{profile?.full_name || 'Chief Executive'}</p>
              <p className="text-[0.625rem] text-on-surface-variant font-medium">CEO</p>
            </div>
            <img alt="CEO Profile" className="w-8 h-8 rounded-full object-cover border border-slate-200" src={profile?.avatar_url || "https://lh3.googleusercontent.com/aida-public/AB6AXuDcIs4T8mIzNJqdWqABuqQuwVvr6_XXPjvrXNnQ-E3F3SeNfVMsgbO1lRsFHkoED8JI2CM1TBQtMdOmsFvGFTCvy8rt_o29mtoW6ocC-3W_Ri37A-U1gel2j1NdzjQnKThBr7IGCFtdrjxgO_JE0eHk29I0gYfda40aV4oeNWYoHazo_aLFDd_gAhjVSmSQjZAZWU1270VCAx8A9diNJ7S6xzzIZ3ICb43Ae9YKXBcE-suvbD8ScbypTWYhzVgw1-RKsgsZpoj5rPZk"} />
          </div>
        </div>
      </header>

      {/* Main Content Stage */}
      <main className="ml-64 pt-24 px-10 pb-12 min-h-screen">
        <header className="mb-10 flex justify-between items-end cursor-default">
          <div>
            <span className="text-[0.6875rem] font-bold uppercase tracking-[0.15em] text-on-surface-variant font-headline">Global Overview</span>
            <h2 className="text-4xl font-extrabold tracking-tight mt-1 text-on-surface font-headline">Executive Terminal</h2>
          </div>
          <div className="flex gap-2">
            <div className="bg-surface-container-low px-4 py-2 flex items-center gap-2 rounded text-xs font-semibold text-on-surface-variant border-transparent">
              <span className="material-symbols-outlined text-sm" data-icon="calendar_today">calendar_today</span>
              Last 30 Days
            </div>
            <button className="bg-primary text-on-primary px-5 py-2 text-xs font-bold rounded hover:opacity-90 transition-all flex items-center gap-2 cursor-pointer">
              <span className="material-symbols-outlined text-sm" data-icon="download">download</span>
              Export Report
            </button>
          </div>
        </header>

        {/* KPI Grid */}
        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8 cursor-default">
          {/* Card 1 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Total Users</span>
              <span className="material-symbols-outlined text-on-primary-container group-hover:scale-110 transition-transform" data-icon="person">person</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">1.24M</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-tertiary-fixed-dim text-on-tertiary-fixed font-bold flex items-center gap-0.5">
                <span className="material-symbols-outlined text-[10px]" data-icon="arrow_upward">arrow_upward</span> 12%
              </span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">vs. last month (1.11M)</p>
          </div>
          
          {/* Card 2 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Tenants Funded</span>
              <span className="material-symbols-outlined text-on-primary-container" data-icon="real_estate_agent">real_estate_agent</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">84.2K</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-tertiary-fixed-dim text-on-tertiary-fixed font-bold flex items-center gap-0.5">
                <span className="material-symbols-outlined text-[10px]" data-icon="arrow_upward">arrow_upward</span> 8.4%
              </span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">Total active rental funding</p>
          </div>

          {/* Card 3 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Rent Financed</span>
              <span className="material-symbols-outlined text-on-primary-container" data-icon="account_balance_wallet">account_balance_wallet</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">$312M</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-tertiary-fixed-dim text-on-tertiary-fixed font-bold flex items-center gap-0.5">
                <span className="material-symbols-outlined text-[10px]" data-icon="arrow_upward">arrow_upward</span> 24%
              </span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">Aggregate portfolio value</p>
          </div>

          {/* Card 4 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Total Landlords</span>
              <span className="material-symbols-outlined text-on-primary-container" data-icon="apartment">apartment</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">14,802</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-tertiary-fixed-dim text-on-tertiary-fixed font-bold flex items-center gap-0.5">
                <span className="material-symbols-outlined text-[10px]" data-icon="arrow_upward">arrow_upward</span> 3.1%
              </span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">Partner property owners</p>
          </div>

          {/* Card 5 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Partners/Investors</span>
              <span className="material-symbols-outlined text-on-primary-container" data-icon="handshake">handshake</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">892</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-secondary-fixed text-on-secondary-container font-bold">Stable</span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">Institutional capital partners</p>
          </div>

          {/* Card 6 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Platform Revenue</span>
              <span className="material-symbols-outlined text-on-primary-container" data-icon="payments">payments</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">$42.8M</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-tertiary-fixed-dim text-on-tertiary-fixed font-bold flex items-center gap-0.5">
                <span className="material-symbols-outlined text-[10px]" data-icon="arrow_upward">arrow_upward</span> 18%
              </span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">Net operational income</p>
          </div>

          {/* Card 7 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Rent Repaid</span>
              <span className="material-symbols-outlined text-on-primary-container" data-icon="verified">verified</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">96.4%</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-tertiary-fixed-dim text-on-tertiary-fixed font-bold flex items-center gap-0.5">
                <span className="material-symbols-outlined text-[10px]" data-icon="add">add</span> 0.5%
              </span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">Collection efficiency rate</p>
          </div>

          {/* Card 8 */}
          <div className="bg-surface-container-lowest p-6 rounded shadow-sm hover:shadow-md transition-shadow group border-transparent">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant">Active Agents</span>
              <span className="material-symbols-outlined text-on-primary-container" data-icon="badge">badge</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold tracking-tight font-headline">5,201</span>
              <span className="text-[0.6875rem] px-2 py-0.5 rounded-full bg-error-container text-on-error-container font-bold flex items-center gap-0.5">
                <span className="material-symbols-outlined text-[10px]" data-icon="arrow_downward">arrow_downward</span> 2.1%
              </span>
            </div>
            <p className="text-[0.6875rem] text-on-surface-variant mt-2">Field operators active</p>
          </div>
        </section>

        {/* Growth Metrics & Charts Row */}
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 mb-8 cursor-default">
          {/* Left: Growth Metrics Panel */}
          <section className="bg-surface-container-low p-8 rounded border-none lg:col-span-1">
            <h3 className="text-sm font-bold uppercase tracking-widest text-on-surface mb-8 font-headline">Growth Metrics</h3>
            <div className="space-y-8">
              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-[0.6875rem] font-bold uppercase text-on-surface-variant">Active Users</p>
                  <p className="text-xl font-extrabold font-headline">942.5K</p>
                </div>
                <div className="h-12 w-24 relative overflow-hidden">
                  <svg className="absolute bottom-0 left-0 w-full h-8" viewBox="0 0 100 40">
                    <path d="M0 35 Q 25 30, 50 15 T 100 5" fill="none" stroke="#000" strokeWidth="2"></path>
                  </svg>
                </div>
              </div>
              
              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-[0.6875rem] font-bold uppercase text-on-surface-variant">New Users</p>
                  <p className="text-xl font-extrabold font-headline">12.1K</p>
                </div>
                <div className="h-12 w-24 relative overflow-hidden">
                  <svg className="absolute bottom-0 left-0 w-full h-8" viewBox="0 0 100 40">
                    <path d="M0 38 Q 30 35, 60 25 T 100 10" fill="none" stroke="#000" strokeWidth="2"></path>
                  </svg>
                </div>
              </div>

              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-[0.6875rem] font-bold uppercase text-on-surface-variant">Retention</p>
                  <p className="text-xl font-extrabold font-headline">88.4%</p>
                </div>
                <div className="h-1.5 w-24 bg-surface-container-high rounded-full overflow-hidden">
                  <div className="bg-primary h-full w-[88%]"></div>
                </div>
              </div>

              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-[0.6875rem] font-bold uppercase text-on-surface-variant">Referral</p>
                  <p className="text-xl font-extrabold font-headline">4.2x</p>
                </div>
                <div className="h-12 w-24 relative overflow-hidden">
                  <svg className="absolute bottom-0 left-0 w-full h-8" viewBox="0 0 100 40">
                    <path d="M0 30 Q 25 35, 50 20 T 100 8" fill="none" stroke="#000" strokeWidth="2"></path>
                  </svg>
                </div>
              </div>

              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-[0.6875rem] font-bold uppercase text-on-surface-variant">Daily Trans.</p>
                  <p className="text-xl font-extrabold font-headline">42.8K</p>
                </div>
                <div className="h-1.5 w-24 bg-surface-container-high rounded-full overflow-hidden">
                  <div className="bg-primary h-full w-[65%]"></div>
                </div>
              </div>
            </div>
          </section>

          {/* Right: 3-Column Chart Row */}
          <section className="lg:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Tenant Growth Chart */}
            <div className="bg-surface-container-lowest p-6 rounded shadow-sm flex flex-col justify-between">
              <div>
                <p className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant mb-4 font-headline">Tenant Growth</p>
                <h4 className="text-2xl font-extrabold font-headline">+18.5%</h4>
              </div>
              <div className="h-32 mt-6 flex items-end gap-1">
                <div className="bg-primary-fixed-dim w-full h-[30%] rounded-t-sm"></div>
                <div className="bg-primary-fixed-dim w-full h-[45%] rounded-t-sm"></div>
                <div className="bg-primary-fixed-dim w-full h-[40%] rounded-t-sm"></div>
                <div className="bg-primary-fixed-dim w-full h-[60%] rounded-t-sm"></div>
                <div className="bg-primary-fixed-dim w-full h-[80%] rounded-t-sm"></div>
                <div className="bg-primary w-full h-[95%] rounded-t-sm"></div>
              </div>
            </div>

            {/* Capital Raised Chart */}
            <div className="bg-surface-container-lowest p-6 rounded shadow-sm flex flex-col justify-between">
              <div>
                <p className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant mb-4 font-headline">Capital Raised</p>
                <h4 className="text-2xl font-extrabold font-headline">$14.2M</h4>
              </div>
              <div className="h-32 mt-6 relative overflow-hidden border-b border-outline-variant/15">
                <svg className="absolute inset-0 w-full h-full" viewBox="0 0 100 50">
                  <polyline fill="none" points="0,40 20,35 40,30 60,15 80,10 100,5" stroke="#000" strokeWidth="3"></polyline>
                  <path d="M0,40 20,35 40,30 60,15 80,10 100,5 100,50 0,50 Z" fill="#000" opacity="0.05"></path>
                </svg>
              </div>
            </div>

            {/* Rent Repayment Chart */}
            <div className="bg-surface-container-lowest p-6 rounded shadow-sm flex flex-col justify-between">
              <div>
                <p className="text-[0.6875rem] font-bold uppercase tracking-widest text-on-surface-variant mb-4 font-headline">Rent Repayment</p>
                <h4 className="text-2xl font-extrabold font-headline">98.2%</h4>
              </div>
              <div className="h-32 mt-6 flex flex-col justify-end gap-4">
                <div className="space-y-2">
                  <div className="flex justify-between text-[10px] font-bold uppercase text-on-surface-variant">
                    <span>Target</span>
                    <span>99%</span>
                  </div>
                  <div className="h-1.5 w-full bg-surface-container-high rounded-full overflow-hidden">
                    <div className="bg-primary-fixed-dim h-full w-[99%]"></div>
                  </div>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between text-[10px] font-bold uppercase text-on-surface-variant">
                    <span>Actual</span>
                    <span>98.2%</span>
                  </div>
                  <div className="h-1.5 w-full bg-surface-container-high rounded-full overflow-hidden">
                    <div className="bg-tertiary-fixed-dim h-full w-[98.2%]"></div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        {/* Recent Rent Requests Table */}
        <section className="bg-surface-container-lowest rounded shadow-sm overflow-hidden cursor-default">
          <div className="px-8 py-6 flex justify-between items-center border-b border-outline-variant/15">
            <h3 className="text-sm font-bold uppercase tracking-widest text-on-surface font-headline">Recent Rent Requests</h3>
            <div className="flex gap-4">
              <nav className="flex gap-2 p-1 bg-surface-container-low rounded">
                <button className="px-3 py-1 text-[10px] font-bold uppercase tracking-tighter bg-surface-container-lowest shadow-sm rounded-sm">All</button>
                <button className="px-3 py-1 text-[10px] font-bold uppercase tracking-tighter text-on-surface-variant hover:text-on-surface rounded-sm">Pending</button>
                <button className="px-3 py-1 text-[10px] font-bold uppercase tracking-tighter text-on-surface-variant hover:text-on-surface rounded-sm">Funded</button>
                <button className="px-3 py-1 text-[10px] font-bold uppercase tracking-tighter text-on-surface-variant hover:text-on-surface rounded-sm">Declined</button>
              </nav>
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="bg-surface-container-low/30">
                  <th className="px-8 py-4 text-left text-[0.625rem] font-black uppercase tracking-widest text-on-surface-variant">Request Date</th>
                  <th className="px-8 py-4 text-left text-[0.625rem] font-black uppercase tracking-widest text-on-surface-variant">Tenant</th>
                  <th className="px-8 py-4 text-left text-[0.625rem] font-black uppercase tracking-widest text-on-surface-variant">Status</th>
                  <th className="px-8 py-4 text-right text-[0.625rem] font-black uppercase tracking-widest text-on-surface-variant">Amount</th>
                  <th className="px-8 py-4 text-right text-[0.625rem] font-black uppercase tracking-widest text-on-surface-variant">Repaid</th>
                  <th className="px-8 py-4 text-right text-[0.625rem] font-black uppercase tracking-widest text-on-surface-variant">Balance</th>
                  <th className="px-8 py-4"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-outline-variant/10">
                {/* Row 1 */}
                <tr className="hover:bg-surface-container-low/20 transition-colors">
                  <td className="px-8 py-5 text-xs font-medium text-on-surface">Oct 24, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-7 h-7 bg-primary-fixed-dim rounded-full flex items-center justify-center text-[10px] font-bold text-on-primary-fixed">ED</div>
                      <span className="text-xs font-semibold text-on-surface">Elena D’Amico</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-2.5 py-1 rounded-full bg-tertiary-fixed-dim/30 text-on-tertiary-fixed text-[10px] font-bold uppercase tracking-tighter">Funded</span>
                  </td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-on-surface">$3,200.00</td>
                  <td className="px-8 py-5 text-right text-xs text-on-surface-variant">$1,600.00</td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-on-surface">$1,600.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="text-on-surface-variant hover:text-primary transition-colors cursor-pointer">
                      <span className="material-symbols-outlined text-sm" data-icon="more_vert">more_vert</span>
                    </button>
                  </td>
                </tr>

                {/* Row 2 */}
                <tr className="hover:bg-surface-container-low/20 transition-colors">
                  <td className="px-8 py-5 text-xs font-medium text-on-surface">Oct 23, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-7 h-7 bg-secondary-fixed-dim rounded-full flex items-center justify-center text-[10px] font-bold text-on-secondary-fixed">MB</div>
                      <span className="text-xs font-semibold text-on-surface">Marcus Bennett</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-2.5 py-1 rounded-full bg-secondary-fixed/50 text-on-secondary-container text-[10px] font-bold uppercase tracking-tighter">Pending</span>
                  </td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-on-surface">$4,500.00</td>
                  <td className="px-8 py-5 text-right text-xs text-on-surface-variant">$0.00</td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-on-surface">$4,500.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="text-on-surface-variant hover:text-primary transition-colors cursor-pointer">
                      <span className="material-symbols-outlined text-sm" data-icon="more_vert">more_vert</span>
                    </button>
                  </td>
                </tr>

                {/* Row 3 */}
                <tr className="hover:bg-surface-container-low/20 transition-colors">
                  <td className="px-8 py-5 text-xs font-medium text-on-surface">Oct 23, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-7 h-7 bg-on-primary-container/20 rounded-full flex items-center justify-center text-[10px] font-bold text-on-primary-container">JL</div>
                      <span className="text-xs font-semibold text-on-surface">Janelle Low</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-2.5 py-1 rounded-full bg-tertiary-fixed-dim/30 text-on-tertiary-fixed text-[10px] font-bold uppercase tracking-tighter">Funded</span>
                  </td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-on-surface">$2,800.00</td>
                  <td className="px-8 py-5 text-right text-xs text-on-surface-variant">$2,800.00</td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-on-tertiary-container">$0.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="text-on-surface-variant hover:text-primary transition-colors cursor-pointer">
                      <span className="material-symbols-outlined text-sm" data-icon="more_vert">more_vert</span>
                    </button>
                  </td>
                </tr>

                {/* Row 4 */}
                <tr className="hover:bg-surface-container-low/20 transition-colors">
                  <td className="px-8 py-5 text-xs font-medium text-on-surface">Oct 22, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-7 h-7 bg-error-container/40 rounded-full flex items-center justify-center text-[10px] font-bold text-on-error-container">TK</div>
                      <span className="text-xs font-semibold text-on-surface">Tariq Khan</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-2.5 py-1 rounded-full bg-error-container text-on-error-container text-[10px] font-bold uppercase tracking-tighter">Overdue</span>
                  </td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-on-surface">$5,000.00</td>
                  <td className="px-8 py-5 text-right text-xs text-on-surface-variant">$1,200.00</td>
                  <td className="px-8 py-5 text-right text-xs font-bold text-error">$3,800.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="text-on-surface-variant hover:text-primary transition-colors cursor-pointer">
                      <span className="material-symbols-outlined text-sm" data-icon="more_vert">more_vert</span>
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="px-8 py-4 bg-surface-container-low/30 flex justify-between items-center border-t border-outline-variant/15">
            <p className="text-[0.625rem] font-bold uppercase tracking-widest text-on-surface-variant">Showing 4 of 1,240 records</p>
            <div className="flex gap-4">
              <button className="text-[0.625rem] font-bold uppercase tracking-widest text-on-surface-variant hover:text-on-surface transition-colors">Previous</button>
              <button className="text-[0.625rem] font-bold uppercase tracking-widest text-on-surface-variant hover:text-on-surface transition-colors">Next</button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
