import React from 'react';
import { useAuth } from '../../contexts/AuthContext';
<<<<<<< HEAD
import { useNavigate } from 'react-router-dom';
import { 
  Users, Home, Briefcase, Building2, Handshake, 
  Wallet, CheckCircle2, UserCheck, Search, Bell, 
  Settings, Calendar, Download, MoreVertical, 
  ArrowUpRight, ArrowDownRight, PieChart, Activity,
  TrendingUp, HelpCircle
} from 'lucide-react';
=======

const ceoColors = `
  .bg-surface { background-color: #f7f9fb; }
  .text-on-surface { color: #191c1e; }
  .bg-surface-container-lowest { background-color: #ffffff; }
  .bg-surface-container-low { background-color: #f2f4f6; }
  .bg-surface-container { background-color: #eceef0; }
  .bg-surface-container-high { background-color: #e6e8ea; }
  .bg-surface-container-highest { background-color: #e0e3e5; }
  
  .text-on-surface-variant { color: #45464d; }
  .text-on-surface { color: #191c1e; }
  
  .bg-primary { background-color: #000000; }
  .text-on-primary { color: #ffffff; }
  .bg-primary-fixed { background-color: #dae2fd; }
  .bg-primary-fixed-dim { background-color: #bec6e0; }
  .text-on-primary-fixed { color: #131b2e; }
  .text-on-primary-container { color: #7c839b; }
  .bg-on-primary-container { background-color: #7c839b; }
  
  .bg-secondary-fixed { background-color: #d5e3fc; }
  .bg-secondary-fixed-dim { background-color: #b9c7df; }
  .text-on-secondary-fixed { color: #0d1c2e; }
  .text-on-secondary-container { color: #57657a; }
  
  .bg-tertiary-fixed { background-color: #6ffbbe; }
  .bg-tertiary-fixed-dim { background-color: #4edea3; }
  .text-on-tertiary-fixed { color: #002113; }
  .text-on-tertiary-container { color: #009668; }
  
  .bg-error-container { background-color: #ffdad6; }
  .text-on-error-container { color: #93000a; }
  .text-error { color: #ba1a1a; }
  
  .border-outline-variant { border-color: #c6c6cd; }
  
  /* Additional Tailwind Utilities typically generated by Config */
  .divide-outline-variant\\/10 > :not([hidden]) ~ :not([hidden]) {
    border-color: rgba(198, 198, 205, 0.1);
  }
  .bg-tertiary-fixed-dim\\/30 { background-color: rgba(78, 222, 163, 0.3); }
  .bg-secondary-fixed\\/50 { background-color: rgba(213, 227, 252, 0.5); }
  .bg-on-primary-container\\/20 { background-color: rgba(124, 131, 155, 0.2); }
  .bg-error-container\\/40 { background-color: rgba(255, 218, 214, 0.4); }
  .bg-surface-container-low\\/30 { background-color: rgba(242, 244, 246, 0.3); }
  .hover\\:bg-surface-container-low\\/20:hover { background-color: rgba(242, 244, 246, 0.2); }
  .border-outline-variant\\/15 { border-color: rgba(198, 198, 205, 0.15); }
`;
>>>>>>> efede9deada22398a9f75ea1e983b4f479a836ae

export default function CeoDashboard() {
  const { profile } = useAuth();

  return (
    <div className="bg-[var(--color-primary-faint)] min-h-screen font-inter text-slate-900 pb-12">
      
      {/* SideNavBar */}
      <aside className="h-screen w-64 fixed left-0 top-0 overflow-y-auto bg-white border-r border-[var(--color-primary-light)] flex flex-col py-8 px-6 z-50">
        <div className="mb-10">
          <h1 className="text-xl font-bold tracking-tight text-[var(--color-primary-darker)] font-outfit">Sovereign</h1>
          <p className="text-[0.6875rem] font-bold uppercase tracking-widest text-slate-400 mt-1">CEO Terminal</p>
        </div>
        
        <nav className="flex-1 space-y-2">
          <a className="flex items-center gap-3 py-2.5 px-3 rounded-xl bg-[var(--color-primary-light)] text-[var(--color-primary)] font-bold transition-all duration-300" href="#">
            <PieChart size={18} />
            <span className="text-sm">Overview</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 rounded-xl text-slate-500 hover:bg-[var(--color-primary-light)] hover:text-[var(--color-primary)] transition-colors duration-200" href="#">
            <Wallet size={18} />
            <span className="text-sm font-medium">Revenue</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 rounded-xl text-slate-500 hover:bg-[var(--color-primary-light)] hover:text-[var(--color-primary)] transition-colors duration-200" href="#">
            <Users size={18} />
            <span className="text-sm font-medium">Users</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 rounded-xl text-slate-500 hover:bg-[var(--color-primary-light)] hover:text-[var(--color-primary)] transition-colors duration-200" href="#">
            <Activity size={18} />
            <span className="text-sm font-medium">Financials</span>
          </a>
          <a className="flex items-center gap-3 py-2.5 px-3 rounded-xl text-slate-500 hover:bg-[var(--color-primary-light)] hover:text-[var(--color-primary)] transition-colors duration-200" href="#">
            <TrendingUp size={18} />
            <span className="text-sm font-medium">Performance</span>
          </a>
        </nav>
        
        <div className="mt-auto pt-8 space-y-2">
          <button className="w-full bg-[var(--color-primary)] text-[var(--color-on-primary)] py-3 rounded-xl text-sm font-bold hover:bg-[var(--color-primary-dark)] active:bg-[var(--color-primary-darker)] transition-all shadow-sm mb-6 flex justify-center items-center gap-2">
            Quick Action
          </button>
          <a className="flex items-center gap-3 py-2 px-3 text-slate-500 hover:bg-slate-50 hover:text-slate-900 rounded-xl transition-colors" href="#">
            <Settings size={18} />
            <span className="text-sm font-medium">Settings</span>
          </a>
          <a className="flex items-center gap-3 py-2 px-3 text-slate-500 hover:bg-slate-50 hover:text-slate-900 rounded-xl transition-colors" href="#">
            <HelpCircle size={18} />
            <span className="text-sm font-medium">Support</span>
          </a>
        </div>
      </aside>

      {/* TopNavBar */}
      <header className="fixed top-0 right-0 w-[calc(100%-16rem)] h-20 bg-white/80 backdrop-blur-xl flex justify-between items-center px-10 z-40 border-b border-[var(--color-primary-light)]">
        <div className="flex items-center gap-8 flex-1">
          <span className="text-xl font-bold tracking-tight text-slate-900 font-outfit">Sovereign Intelligence</span>
          <div className="relative max-w-md w-full ml-4">
            <Search size={18} className="text-[var(--color-primary)] absolute left-4 top-1/2 -translate-y-1/2" />
            <input className="bg-[var(--color-primary-faint)] border border-[var(--color-primary-light)] rounded-full pl-11 pr-4 py-2.5 text-sm w-full focus:ring-2 focus:ring-[var(--color-primary-light)] focus:bg-white transition-all outline-none" placeholder="Intelligence search..." type="text" />
          </div>
        </div>
        <div className="flex items-center gap-6">
          <button className="p-2 text-slate-400 hover:text-[var(--color-primary)] bg-[var(--color-primary-faint)] hover:bg-[var(--color-primary-light)] rounded-full relative transition-all">
            <Bell size={20} />
            <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-red-500 rounded-full border-2 border-white"></span>
          </button>
          <button className="p-2 text-slate-400 hover:text-[var(--color-primary)] bg-[var(--color-primary-faint)] hover:bg-[var(--color-primary-light)] rounded-full transition-all">
            <Settings size={20} />
          </button>
          
          <div className="h-8 w-px bg-[var(--color-primary-light)] mx-2"></div>
          
          <div className="flex items-center gap-3 cursor-pointer group">
            <div className="text-right">
              <p className="text-xs font-bold uppercase tracking-tight text-[var(--color-primary-darker)]">{profile?.full_name || 'Chief Executive'}</p>
              <p className="text-[10px] text-slate-500 font-bold uppercase">CEO</p>
            </div>
            <img alt="CEO Profile" className="w-10 h-10 rounded-full object-cover border-2 border-[var(--color-primary-light)]" src={profile?.avatar_url || "https://lh3.googleusercontent.com/aida-public/AB6AXuDcIs4T8mIzNJqdWqABuqQuwVvr6_XXPjvrXNnQ-E3F3SeNfVMsgbO1lRsFHkoED8JI2CM1TBQtMdOmsFvGFTCvy8rt_o29mtoW6ocC-3W_Ri37A-U1gel2j1NdzjQnKThBr7IGCFtdrjxgO_JE0eHk29I0gYfda40aV4oeNWYoHazo_aLFDd_gAhjVSmSQjZAZWU1270VCAx8A9diNJ7S6xzzIZ3ICb43Ae9YKXBcE-suvbD8ScbypTWYhzVgw1-RKsgsZpoj5rPZk"} />
          </div>
        </div>
      </header>

      {/* Main Content Stage */}
      <main className="ml-64 pt-28 px-10 max-w-screen-2xl mx-auto">
        <header className="mb-8 flex justify-between items-end">
          <div>
            <span className="text-[0.6875rem] font-bold uppercase tracking-[0.15em] text-[var(--color-primary)] font-inter">Global Overview</span>
            <h2 className="text-4xl font-bold tracking-tight mt-2 text-slate-900 font-outfit">Executive Terminal</h2>
          </div>
          <div className="flex gap-3">
            <div className="bg-white px-4 py-2.5 flex items-center gap-2 rounded-full text-xs font-bold text-slate-600 border border-[var(--color-primary-light)] shadow-sm">
              <Calendar size={16} className="text-slate-400" />
              Last 30 Days
            </div>
            <button className="bg-[var(--color-primary)] text-[var(--color-on-primary)] px-6 py-2.5 text-xs font-bold rounded-full hover:bg-[var(--color-primary-dark)] shadow-sm transition-all flex items-center gap-2 cursor-pointer">
              <Download size={16} />
              Export Report
            </button>
          </div>
        </header>

        {/* KPI Grid */}
        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {/* Card 1 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Total Users</span>
              <div className="p-2 bg-[var(--color-primary-light)] text-[var(--color-primary)] rounded-full">
                <Users size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2">1.24M</h3>
              <div className="inline-flex items-center text-[var(--color-success)] text-xs font-bold bg-green-50 px-2 py-1 rounded-md">
                <ArrowUpRight size={14} className="mr-1" /> 12% vs last month
              </div>
            </div>
          </div>
          
          {/* Card 2 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Tenants Funded</span>
              <div className="p-2 bg-[#e0f2fe] text-[#0284c7] rounded-full">
                <Home size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2">84.2K</h3>
              <div className="inline-flex items-center text-[var(--color-success)] text-xs font-bold bg-green-50 px-2 py-1 rounded-md">
                <ArrowUpRight size={14} className="mr-1" /> 8.4%
              </div>
            </div>
          </div>

          {/* Card 3 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Rent Financed</span>
              <div className="p-2 bg-[var(--color-primary-light)] text-[var(--color-primary)] rounded-full">
                <Briefcase size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2"><span className="text-xl text-slate-400 mr-1">$</span>312M</h3>
              <div className="inline-flex items-center text-[var(--color-success)] text-xs font-bold bg-green-50 px-2 py-1 rounded-md">
                <ArrowUpRight size={14} className="mr-1" /> 24%
              </div>
            </div>
          </div>

          {/* Card 4 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Total Landlords</span>
              <div className="p-2 bg-[#ffedd5] text-[#c2410c] rounded-full">
                <Building2 size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2">14,802</h3>
              <div className="inline-flex items-center text-[var(--color-success)] text-xs font-bold bg-green-50 px-2 py-1 rounded-md">
                <ArrowUpRight size={14} className="mr-1" /> 3.1%
              </div>
            </div>
          </div>

          {/* Card 5 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Partners/Investors</span>
              <div className="p-2 bg-[var(--color-primary-light)] text-[var(--color-primary)] rounded-full">
                <Handshake size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2">892</h3>
              <div className="inline-flex items-center text-slate-600 text-xs font-bold bg-slate-100 px-2 py-1 rounded-md">
                Stable Target
              </div>
            </div>
          </div>

          {/* Card 6 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Platform Revenue</span>
              <div className="p-2 bg-green-50 text-[var(--color-success)] rounded-full">
                <Wallet size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2"><span className="text-xl text-slate-400 mr-1">$</span>42.8M</h3>
              <div className="inline-flex items-center text-[var(--color-success)] text-xs font-bold bg-green-50 px-2 py-1 rounded-md">
                <ArrowUpRight size={14} className="mr-1" /> 18%
              </div>
            </div>
          </div>

          {/* Card 7 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Rent Repaid</span>
              <div className="p-2 bg-[#dcfce7] text-[var(--color-success)] rounded-full">
                <CheckCircle2 size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2">96.4%</h3>
              <div className="inline-flex items-center text-[var(--color-success)] text-xs font-bold bg-green-50 px-2 py-1 rounded-md">
                <ArrowUpRight size={14} className="mr-1" /> +0.5%
              </div>
            </div>
          </div>

          {/* Card 8 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
            <div className="flex justify-between items-start mb-4">
              <span className="text-slate-500 text-sm font-bold">Active Agents</span>
              <div className="p-2 bg-[var(--color-primary-light)] text-[var(--color-primary)] rounded-full">
                <UserCheck size={18} />
              </div>
            </div>
            <div className="mt-2">
              <h3 className="text-3xl font-bold font-outfit text-slate-900 mb-2">5,201</h3>
              <div className="inline-flex items-center text-red-600 text-xs font-bold bg-red-50 px-2 py-1 rounded-md">
                <ArrowDownRight size={14} className="mr-1" /> 2.1%
              </div>
            </div>
          </div>
        </section>

        {/* Growth Metrics & Charts Row */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
          {/* Left: Growth Metrics Panel */}
          <section className="bg-white border border-slate-100 p-8 rounded-3xl shadow-sm lg:col-span-1 flex flex-col">
            <h3 className="text-lg font-bold text-[var(--color-primary-darker)] mb-8 font-outfit">Growth Metrics</h3>
            <div className="space-y-8 flex-1">
              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-sm font-bold text-slate-500 mb-1">Active Users</p>
                  <p className="text-2xl font-bold font-outfit text-slate-900">942.5K</p>
                </div>
                <div className="h-10 w-24 relative overflow-hidden">
                  <svg className="absolute bottom-0 left-0 w-full h-8" viewBox="0 0 100 40">
                    <path d="M0 35 Q 25 30, 50 15 T 100 5" fill="none" stroke="var(--color-primary)" strokeWidth="3"></path>
                  </svg>
                </div>
              </div>
              
              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-sm font-bold text-slate-500 mb-1">New Users</p>
                  <p className="text-2xl font-bold font-outfit text-slate-900">12.1K</p>
                </div>
                <div className="h-10 w-24 relative overflow-hidden">
                  <svg className="absolute bottom-0 left-0 w-full h-8" viewBox="0 0 100 40">
                    <path d="M0 38 Q 30 35, 60 25 T 100 10" fill="none" stroke="var(--color-primary-dark)" strokeWidth="3"></path>
                  </svg>
                </div>
              </div>

              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-sm font-bold text-slate-500 mb-1">Retention</p>
                  <p className="text-2xl font-bold font-outfit text-slate-900">88.4%</p>
                </div>
                <div className="h-2 w-24 bg-slate-100 rounded-full overflow-hidden self-center">
                  <div className="bg-[var(--color-success)] h-full w-[88%] rounded-full"></div>
                </div>
              </div>

              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-sm font-bold text-slate-500 mb-1">Referral</p>
                  <p className="text-2xl font-bold font-outfit text-slate-900">4.2x</p>
                </div>
                <div className="h-10 w-24 relative overflow-hidden">
                  <svg className="absolute bottom-0 left-0 w-full h-8" viewBox="0 0 100 40">
                    <path d="M0 30 Q 25 35, 50 20 T 100 8" fill="none" stroke="#c2410c" strokeWidth="3"></path>
                  </svg>
                </div>
              </div>

              <div className="flex justify-between items-center group">
                <div>
                  <p className="text-sm font-bold text-slate-500 mb-1">Daily Trans.</p>
                  <p className="text-2xl font-bold font-outfit text-slate-900">42.8K</p>
                </div>
                <div className="h-2 w-24 bg-slate-100 rounded-full overflow-hidden self-center">
                  <div className="bg-[var(--color-primary)] h-full w-[65%] rounded-full"></div>
                </div>
              </div>
            </div>
          </section>

          {/* Right: Charts Row */}
          <section className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* Chart 1: Tenant Growth */}
            <div className="bg-white p-6 md:p-8 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
              <div>
                <p className="text-sm font-bold text-[var(--color-primary)] mb-2">Tenant Growth</p>
                <h4 className="text-3xl font-bold font-outfit text-slate-900">+18.5%</h4>
              </div>
              <div className="h-40 mt-8 flex items-end gap-2">
                <div className="bg-[var(--color-primary-light)] w-full h-[30%] rounded-md hover:bg-[var(--color-primary)] transition-colors"></div>
                <div className="bg-[var(--color-primary-light)] w-full h-[45%] rounded-md hover:bg-[var(--color-primary)] transition-colors"></div>
                <div className="bg-[var(--color-primary-light)] w-full h-[40%] rounded-md hover:bg-[var(--color-primary)] transition-colors"></div>
                <div className="bg-[var(--color-primary-light)] w-full h-[60%] rounded-md hover:bg-[var(--color-primary)] transition-colors"></div>
                <div className="bg-[var(--color-primary-light)] w-full h-[80%] rounded-md hover:bg-[var(--color-primary)] transition-colors"></div>
                <div className="bg-[var(--color-primary)] w-full h-[95%] rounded-md shadow-md"></div>
              </div>
            </div>

            {/* Chart 2: Rent Repayment Focus */}
            <div className="bg-white p-6 md:p-8 rounded-3xl border border-slate-100 shadow-sm flex flex-col justify-between">
              <div>
                <p className="text-sm font-bold text-[var(--color-primary)] mb-2">Rent Repayment</p>
                <h4 className="text-3xl font-bold font-outfit text-slate-900">98.2%</h4>
              </div>
              <div className="h-40 flex flex-col justify-end gap-6 mt-6">
                <div>
                  <div className="flex justify-between text-xs font-bold text-slate-600 mb-2">
                    <span>Target Target</span>
                    <span className="text-[var(--color-primary)] bg-[var(--color-primary-light)] px-2 py-0.5 rounded-md">99%</span>
                  </div>
                  <div className="h-2 w-full bg-[var(--color-primary-faint)] rounded-full overflow-hidden border border-[var(--color-primary-light)]">
                    <div className="bg-[var(--color-primary)] h-full w-[99%] rounded-full"></div>
                  </div>
                </div>
                <div>
                  <div className="flex justify-between text-xs font-bold text-slate-600 mb-2">
                    <span>Actual Metric</span>
                    <span className="text-[var(--color-success)] bg-green-50 px-2 py-0.5 rounded-md">98.2%</span>
                  </div>
                  <div className="h-2 w-full bg-[var(--color-primary-faint)] rounded-full overflow-hidden border border-[var(--color-primary-light)]">
                    <div className="bg-[var(--color-success)] h-full w-[98.2%] rounded-full"></div>
                  </div>
                </div>
              </div>
            </div>

          </section>
        </div>

        {/* Recent Rent Requests Table */}
        <section className="bg-white border border-[var(--color-primary-light)] rounded-3xl shadow-sm overflow-hidden mb-12">
          <div className="px-8 py-6 flex justify-between items-center border-b border-[var(--color-primary-light)]">
            <h3 className="text-lg font-bold text-[var(--color-primary-darker)] font-outfit">Recent Funding Requests</h3>
            <div className="flex gap-2 p-1 bg-[var(--color-primary-faint)] rounded-xl border border-[var(--color-primary-light)]">
              <button className="px-4 py-1.5 text-xs font-bold text-[var(--color-primary-darker)] bg-white shadow-sm rounded-lg">All</button>
              <button className="px-4 py-1.5 text-xs font-bold text-[var(--color-primary)] hover:text-[var(--color-primary-darker)] rounded-lg transition-colors">Pending</button>
              <button className="px-4 py-1.5 text-xs font-bold text-[var(--color-primary)] hover:text-[var(--color-primary-darker)] rounded-lg transition-colors">Funded</button>
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-[var(--color-primary-faint)] border-b border-[var(--color-primary-light)]">
                  <th className="px-8 py-4 text-xs font-bold text-[var(--color-primary)] uppercase tracking-widest whitespace-nowrap">Request Date</th>
                  <th className="px-8 py-4 text-xs font-bold text-[var(--color-primary)] uppercase tracking-widest whitespace-nowrap">Tenant</th>
                  <th className="px-8 py-4 text-xs font-bold text-[var(--color-primary)] uppercase tracking-widest whitespace-nowrap">Status</th>
                  <th className="px-8 py-4 text-xs font-bold text-[var(--color-primary)] uppercase tracking-widest text-right whitespace-nowrap">Amount</th>
                  <th className="px-8 py-4 text-xs font-bold text-[var(--color-primary)] uppercase tracking-widest text-right whitespace-nowrap">Repaid</th>
                  <th className="px-8 py-4 text-xs font-bold text-[var(--color-primary)] uppercase tracking-widest text-right whitespace-nowrap">Balance</th>
                  <th className="px-8 py-4"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--color-primary-light)]">
                {/* Row 1 */}
                <tr className="hover:bg-[var(--color-primary-faint)] transition-colors">
                  <td className="px-8 py-5 text-sm font-medium text-slate-600">Oct 24, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 bg-[var(--color-primary-light)] text-[var(--color-primary)] rounded-full flex items-center justify-center text-xs font-bold">ED</div>
                      <span className="text-sm font-bold text-slate-900">Elena D’Amico</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-3 py-1.5 rounded-lg bg-green-50 text-[var(--color-success)] text-xs font-bold">Funded</span>
                  </td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-slate-900">$3,200.00</td>
                  <td className="px-8 py-5 text-right text-sm font-medium text-[var(--color-primary)]">$1,600.00</td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-slate-900">$1,600.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="p-2 text-slate-400 hover:text-[var(--color-primary)] hover:bg-[var(--color-primary-light)] rounded-full transition-all">
                      <MoreVertical size={16} />
                    </button>
                  </td>
                </tr>

                {/* Row 2 */}
                <tr className="hover:bg-[var(--color-primary-faint)] transition-colors">
                  <td className="px-8 py-5 text-sm font-medium text-slate-600">Oct 23, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 bg-[var(--color-warning-bg)] text-[var(--color-warning)] rounded-full flex items-center justify-center text-xs font-bold">MB</div>
                      <span className="text-sm font-bold text-slate-900">Marcus Bennett</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-3 py-1.5 rounded-lg bg-[var(--color-warning-bg)] text-[var(--color-warning)] text-xs font-bold">Pending</span>
                  </td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-slate-900">$4,500.00</td>
                  <td className="px-8 py-5 text-right text-sm font-medium text-[var(--color-primary)]">$0.00</td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-slate-900">$4,500.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="p-2 text-slate-400 hover:text-[var(--color-primary)] hover:bg-[var(--color-primary-light)] rounded-full transition-all">
                      <MoreVertical size={16} />
                    </button>
                  </td>
                </tr>

                {/* Row 3 */}
                <tr className="hover:bg-[var(--color-primary-faint)] transition-colors">
                  <td className="px-8 py-5 text-sm font-medium text-slate-600">Oct 23, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 bg-[#fdf4ff] text-[#c026d3] rounded-full flex items-center justify-center text-xs font-bold">JL</div>
                      <span className="text-sm font-bold text-slate-900">Janelle Low</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-3 py-1.5 rounded-lg bg-green-50 text-[var(--color-success)] text-xs font-bold">Funded</span>
                  </td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-slate-900">$2,800.00</td>
                  <td className="px-8 py-5 text-right text-sm font-medium text-[var(--color-primary)]">$2,800.00</td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-[var(--color-success)]">$0.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="p-2 text-slate-400 hover:text-[var(--color-primary)] hover:bg-[var(--color-primary-light)] rounded-full transition-all">
                      <MoreVertical size={16} />
                    </button>
                  </td>
                </tr>

                {/* Row 4 */}
                <tr className="hover:bg-[var(--color-primary-faint)] transition-colors">
                  <td className="px-8 py-5 text-sm font-medium text-slate-600">Oct 22, 2023</td>
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 bg-red-50 text-red-600 rounded-full flex items-center justify-center text-xs font-bold">TK</div>
                      <span className="text-sm font-bold text-slate-900">Tariq Khan</span>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-3 py-1.5 rounded-lg bg-red-50 text-red-600 text-xs font-bold">Overdue</span>
                  </td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-slate-900">$5,000.00</td>
                  <td className="px-8 py-5 text-right text-sm font-medium text-red-500">$1,200.00</td>
                  <td className="px-8 py-5 text-right text-sm font-bold text-red-600">$3,800.00</td>
                  <td className="px-8 py-5 text-right">
                    <button className="p-2 text-slate-400 hover:text-[var(--color-primary)] hover:bg-[var(--color-primary-light)] rounded-full transition-all">
                      <MoreVertical size={16} />
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="px-8 py-5 bg-[var(--color-primary-faint)] flex justify-between items-center border-t border-[var(--color-primary-light)]">
            <p className="text-sm font-medium text-slate-500">Showing <span className="font-bold text-slate-900">4</span> of <span className="font-bold text-slate-900">1,240</span> records</p>
            <div className="flex gap-2">
              <button className="px-4 py-2 text-xs font-bold text-[var(--color-primary)] bg-white border border-[var(--color-primary-light)] rounded-lg hover:bg-[var(--color-primary-faint)] transition-colors">Previous</button>
              <button className="px-4 py-2 text-xs font-bold text-[var(--color-primary)] bg-white border border-[var(--color-primary-light)] rounded-lg hover:bg-[var(--color-primary-faint)] transition-colors">Next</button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
