// jsPDF loaded dynamically to reduce initial bundle size

import { formatDynamic as formatUGX } from '@/lib/currencyFormat';

interface PaymentRow {
  tenant_name?: string;
  tenant_phone: string;
  amount: number;
  merchant_name: string;
  transaction_id: string;
  created_at: string;
  notes: string | null;
}

interface AgentReportData {
  agentName: string;
  totalCollected: number;
  paymentCount: number;
  payments: PaymentRow[];
}

export async function generateAgentReportPdf(data: AgentReportData): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4', compress: true });
  const pw = pdf.internal.pageSize.getWidth();
  const margin = 12;
  let y = margin;

  // Header
  pdf.setFillColor(88, 28, 135); // purple-900
  pdf.rect(0, 0, pw, 28, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Welile — Agent Collection Report', margin, 12);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated: ${new Date().toLocaleDateString('en-UG', { dateStyle: 'full' })}`, margin, 20);
  pdf.text(`Agent: ${data.agentName}`, margin, 25);
  y = 34;

  // Summary box
  pdf.setTextColor(0, 0, 0);
  pdf.setFillColor(240, 253, 244); // green-50
  pdf.roundedRect(margin, y, pw - margin * 2, 14, 2, 2, 'F');
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total Collected: ${formatUGX(data.totalCollected)}`, margin + 4, y + 6);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`${data.paymentCount} payment${data.paymentCount !== 1 ? 's' : ''} recorded`, margin + 4, y + 11);
  y += 20;

  // Table header
  const cols = [margin, margin + 45, margin + 80, margin + 120, margin + 155];
  const colLabels = ['Tenant', 'Phone', 'Amount', 'Merchant', 'Date'];
  pdf.setFillColor(243, 244, 246); // gray-100
  pdf.rect(margin, y, pw - margin * 2, 7, 'F');
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(55, 65, 81);
  colLabels.forEach((label, i) => pdf.text(label, cols[i] + 2, y + 5));
  y += 9;

  // Rows
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(0, 0, 0);
  const rowH = 8;

  for (const p of data.payments) {
    if (y + rowH > pdf.internal.pageSize.getHeight() - 20) {
      pdf.addPage();
      y = margin;
    }

    const dateStr = new Date(p.created_at).toLocaleDateString('en-UG', { month: 'short', day: 'numeric', year: '2-digit' });
    const tenantLabel = p.tenant_name || '—';

    pdf.setFontSize(7.5);
    pdf.text(tenantLabel.substring(0, 22), cols[0] + 2, y + 5);
    pdf.text(p.tenant_phone || '—', cols[1] + 2, y + 5);
    pdf.setFont('helvetica', 'bold');
    pdf.text(formatUGX(p.amount), cols[2] + 2, y + 5);
    pdf.setFont('helvetica', 'normal');
    pdf.text((p.merchant_name || '—').substring(0, 18), cols[3] + 2, y + 5);
    pdf.text(dateStr, cols[4] + 2, y + 5);

    // Alternate row bg
    if (data.payments.indexOf(p) % 2 === 1) {
      pdf.setFillColor(249, 250, 251);
      pdf.rect(margin, y, pw - margin * 2, rowH, 'F');
      // Redraw text on top of bg
      pdf.setTextColor(0, 0, 0);
      pdf.setFontSize(7.5);
      pdf.text(tenantLabel.substring(0, 22), cols[0] + 2, y + 5);
      pdf.text(p.tenant_phone || '—', cols[1] + 2, y + 5);
      pdf.setFont('helvetica', 'bold');
      pdf.text(formatUGX(p.amount), cols[2] + 2, y + 5);
      pdf.setFont('helvetica', 'normal');
      pdf.text((p.merchant_name || '—').substring(0, 18), cols[3] + 2, y + 5);
      pdf.text(dateStr, cols[4] + 2, y + 5);
    }

    y += rowH;
  }

  // Footer
  y += 6;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, y, pw - margin, y);
  y += 6;
  pdf.setFontSize(8);
  pdf.setTextColor(120, 120, 120);
  pdf.text('This report was generated by Welile. For support contact +256708257899', margin, y);

  return pdf.output('blob');
}

export function buildAgentReportWhatsAppText(data: AgentReportData): string {
  const lines = [
    `📊 *Welile Agent Report*`,
    `━━━━━━━━━━━━━━━━`,
    `👤 *Agent:* ${data.agentName}`,
    `💰 *Total Collected:* ${formatUGX(data.totalCollected)}`,
    `📝 *Payments:* ${data.paymentCount}`,
    `━━━━━━━━━━━━━━━━`,
    '',
  ];

  for (const p of data.payments.slice(0, 20)) {
    const date = new Date(p.created_at).toLocaleDateString('en-UG', { month: 'short', day: 'numeric' });
    lines.push(`• ${p.tenant_name || p.tenant_phone} — ${formatUGX(p.amount)} (${date})`);
  }

  if (data.payments.length > 20) {
    lines.push(`... and ${data.payments.length - 20} more`);
  }

  lines.push('', `━━━━━━━━━━━━━━━━`, `Powered by Welile`);
  return lines.join('\n');
}
