import jsPDF from 'jspdf';
import { format } from 'date-fns';

interface TenantRow {
  tenant_name: string;
  tenant_phone: string;
  rent_amount: number;
  amount_repaid: number;
  outstanding: number;
  wallet_balance: number;
  status: string;
}

interface AgentInfo {
  full_name: string;
  phone: string;
  tenant_count: number;
}

export function generateAgentTenantPdf(agent: AgentInfo, tenants: TenantRow[]): Blob {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 12;
  const contentWidth = pageWidth - margin * 2;
  let y = 15;

  const ugx = (n: number) => `UGX ${n.toLocaleString()}`;

  // Header
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('WELILE', margin, y);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(format(new Date(), 'dd MMM yyyy, hh:mm a'), pageWidth - margin, y, { align: 'right' });
  y += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Tenant Balances Report', margin, y);
  y += 7;

  // Agent info
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Agent: ${agent.full_name}`, margin, y);
  doc.text(`Phone: ${agent.phone}`, margin + 80, y);
  y += 5;
  doc.text(`Total Tenants: ${tenants.length}`, margin, y);
  y += 8;

  // Table header
  const cols = [
    { label: '#', x: margin, w: 7 },
    { label: 'Tenant Name', x: margin + 7, w: 38 },
    { label: 'Phone', x: margin + 45, w: 28 },
    { label: 'Rent', x: margin + 73, w: 25 },
    { label: 'Repaid', x: margin + 98, w: 25 },
    { label: 'Due Balance', x: margin + 123, w: 28 },
    { label: 'Wallet', x: margin + 151, w: 25 },
  ];

  const drawHeader = () => {
    doc.setFillColor(30, 30, 60);
    doc.rect(margin, y - 4, contentWidth, 6, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    cols.forEach(c => doc.text(c.label, c.x + 1, y));
    doc.setTextColor(0, 0, 0);
    y += 5;
  };

  drawHeader();

  // Table rows
  let totalOutstanding = 0;
  let totalRepaid = 0;

  tenants.forEach((t, i) => {
    if (y > 275) {
      doc.addPage();
      y = 15;
      drawHeader();
    }

    const isEven = i % 2 === 0;
    if (isEven) {
      doc.setFillColor(245, 245, 250);
      doc.rect(margin, y - 3.5, contentWidth, 5, 'F');
    }

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}`, cols[0].x + 1, y);
    doc.text(t.tenant_name.slice(0, 22), cols[1].x + 1, y);
    doc.text(t.tenant_phone || '—', cols[2].x + 1, y);
    doc.text(ugx(t.rent_amount), cols[3].x + 1, y);
    doc.setTextColor(0, 130, 50);
    doc.text(ugx(t.amount_repaid), cols[4].x + 1, y);

    if (t.outstanding > 0) {
      doc.setTextColor(200, 30, 30);
    } else {
      doc.setTextColor(0, 130, 50);
    }
    doc.setFont('helvetica', 'bold');
    doc.text(ugx(t.outstanding), cols[5].x + 1, y);

    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.text(ugx(t.wallet_balance), cols[6].x + 1, y);

    totalOutstanding += t.outstanding;
    totalRepaid += t.amount_repaid;
    y += 5;
  });

  // Summary row
  y += 3;
  doc.setFillColor(30, 30, 60);
  doc.rect(margin, y - 4, contentWidth, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTALS', cols[1].x + 1, y);
  doc.text(ugx(totalRepaid), cols[4].x + 1, y);
  doc.text(ugx(totalOutstanding), cols[5].x + 1, y);
  doc.setTextColor(0, 0, 0);

  // Footer
  y += 12;
  if (y > 280) { doc.addPage(); y = 15; }
  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by Welile Technologies Ltd. This is an automated report.', margin, y);
  doc.text(`Report date: ${format(new Date(), 'PPpp')}`, margin, y + 4);

  return doc.output('blob');
}
